const geometry=window.recordingFrameGeometry,bridge=window.recordingFrame,$=id=>document.getElementById(id);
let state=null,gesture=null,hit=false,latest=null,sending=false;
const call=async(name,value)=>{const result=await bridge.call(name,value);if(!result.ok)throw Error(result.error);return result.value;};
function passthrough(interactive){if(interactive!==hit){hit=interactive;bridge.hit(hit);}}
function paint(rect){if(!state?.bounds||!rect)return;Object.assign($('outline').style,{left:rect.x+'px',top:rect.y+'px',width:rect.width+'px',height:rect.height+'px'});const bar=geometry.toolbar(rect,state.bounds);Object.assign($('toolbar').style,{left:bar.x+'px',top:bar.y+'px',width:bar.width+'px',height:bar.height+'px'});$('toolbar').dataset.inside=String(bar.inside);$('size').textContent=Math.round(rect.width*state.scale)+' × '+Math.round(rect.height*state.scale);}
function render(value){state=value;if(!value.rect)return;window.lunaI18n.setLanguage(value.language);paint(gesture?gesture.current:value.rect);const adjusting=value.phase==='adjusting';document.body.classList.toggle('locked',!adjusting);document.body.classList.toggle('recording',value.phase==='recording');$('start').hidden=!adjusting;$('stop').hidden=adjusting;$('stop').disabled=!['preparing','recording'].includes(value.phase);$('cancel').hidden=!adjusting;for(const [id,text]of [['start','开始录制'],['stop','停止并收藏视频'],['cancel','取消录屏']]){$(id).title=window.lunaI18n.t(text);$(id).setAttribute('aria-label',$(id).title);}}
bridge.onStatus(render);call('recording-state').then(render).catch(()=>{});
async function flush(){if(sending)return;sending=true;try{while(latest){const rect=latest;latest=null;await call('recording-adjust',rect);}}catch{latest=null;}finally{sending=false;}}
document.addEventListener('pointerdown',event=>{const edge=event.target.closest('[data-edge]')?.dataset.edge;if(!edge||state?.phase!=='adjusting'||event.button!==0)return;gesture={edge,x:event.clientX,y:event.clientY,rect:{...state.rect},current:{...state.rect},target:event.target};event.target.setPointerCapture(event.pointerId);passthrough(true);event.preventDefault();});
document.addEventListener('pointermove',event=>{if(gesture){gesture.current=geometry.drag(gesture.rect,gesture.edge,event.clientX-gesture.x,event.clientY-gesture.y,state.bounds);paint(gesture.current);latest=gesture.current;flush();}else passthrough(!!event.target.closest('#toolbar')||state?.phase==='adjusting'&&!!event.target.closest('[data-edge]'));});
function release(event){if(!gesture)return;latest=gesture.current;if(gesture.target.hasPointerCapture(event.pointerId))gesture.target.releasePointerCapture(event.pointerId);gesture=null;flush();passthrough(!!event.target.closest('#toolbar,[data-edge]'));}
document.addEventListener('pointerup',release);document.addEventListener('pointercancel',release);document.addEventListener('lostpointercapture',()=>{gesture=null;flush();});document.addEventListener('mouseleave',()=>{if(!gesture)passthrough(false);});
$('start').onclick=async()=>{if(gesture)return;$('start').disabled=true;await flush();while(sending)await new Promise(resolve=>setTimeout(resolve,10));call('recording-start').catch(()=>{$('start').disabled=false;});};
$('stop').onclick=()=>call('recording-stop').catch(()=>{});$('cancel').onclick=()=>call('recording-stop').catch(()=>{});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&state?.phase==='adjusting')call('recording-stop').catch(()=>{});});
