const test=require('node:test'),assert=require('node:assert/strict');
const {createShortcutBubbles,dateText,statsText,weatherText}=require('../shortcut-bubbles');
const {createPetFeedback}=require('../pet-feedback');
function fixture(){const tasks=[],rendered=[];let count=0;const feedback=createPetFeedback({render:value=>rendered.push(value),schedule:(fn,delay)=>{tasks.push({fn,delay});return tasks.length;},cancel:()=>{}});const controller=createShortcutBubbles({show:feedback.show,update:feedback.update,requestStats:async()=>({cpu:++count,memory:50,gpu:null}),requestWeather:async()=>({status:'unset'}),now:()=>new Date(2026,9,7,10,1,5),schedule:(fn,delay)=>{tasks.push({fn,delay});return tasks.length;},cancel:()=>{}});return {tasks,rendered,controller,feedback,get count(){return count;}};}
test('日期时间用自然对话表示当地日期、星期和时段；缺失硬件读数不伪装为 0%',()=>{assert.equal(dateText(new Date(2026,9,8,10,1,5)),'今天是2026年10月8日，星期四。\n现在是上午10点01分哦。');for(const [hour,expected]of [[0,'凌晨零点整'],[5,'凌晨5点整'],[6,'上午6点整'],[12,'中午12点整'],[13,'下午1点整'],[18,'晚上6点整'],[23,'晚上11点整']])assert.ok(dateText(new Date(2026,9,8,hour,0)).includes(expected));assert.ok(dateText(new Date(2027,0,1,0,1)).startsWith('今天是2027年1月1日，星期五。'));assert.match(statsText({cpu:0,memory:100,gpu:null}),/CPU 0%.*内存 100%\nGPU 暂不可用/);assert.match(weatherText({status:'unset'}),/设置/);assert.match(weatherText({status:'stale',location:{name:'杭州'},reading:{label:'晴',temperature:24.4}}),/杭州.*24°C\n上次天气/);});
test('系统信息先提示读取，更新不延长五秒期限，关闭后晚到回调不再显示',async()=>{const f=fixture();f.controller.start('stats');assert.equal(f.rendered.at(-1).message,'正在读取系统信息…');await Promise.resolve();assert.match(f.rendered.at(-1).message,/CPU 1%/);const tick=f.tasks.find(task=>task.delay===1000);await tick.fn();assert.match(f.rendered.at(-1).message,/CPU 2%/);assert.equal(f.tasks.filter(task=>task.delay===5000).length,2);f.controller.cancel();f.feedback.advance();await tick.fn();assert.equal(f.rendered.at(-1).message,'');assert.equal(f.count,2);});
test('首轮采样等待、真实不可用与真实零占用分别显示',()=>{
  assert.equal(statsText({cpu:null,memory:50,gpu:null,pending:{cpu:true,gpu:true}}),'CPU 读取中 · 内存 50%\nGPU 读取中');
  assert.equal(statsText({cpu:0,memory:50,gpu:null,pending:{cpu:false,gpu:false}}),'CPU 0% · 内存 50%\nGPU 暂不可用');
});
test('天气请求响应迟到不能覆盖下一条消息、已关闭气泡或提醒',async()=>{let finish;const rendered=[],feedback=createPetFeedback({render:value=>rendered.push(value),schedule:()=>1,cancel:()=>{}});const controller=createShortcutBubbles({show:feedback.show,update:feedback.update,requestWeather:()=>new Promise(resolve=>finish=resolve),schedule:()=>1,cancel:()=>{}});controller.start('weather');await Promise.resolve();controller.cancel();feedback.show('其他消息',0);finish({status:'unset'});await Promise.resolve();await Promise.resolve();assert.equal(rendered.at(-1).message,'其他消息');controller.start('weather');await Promise.resolve();feedback.updateReminder({id:'due',title:'喝水',remaining:1});finish({status:'unset'});await Promise.resolve();await Promise.resolve();assert.equal(rendered.at(-1).reminder.id,'due');controller.stop();});
